services:
  db:
    container_name: db
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=coffee_bd
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=sami1234

  test-db:
    container_name: test-db
    image: postgres:14-alpine
    ports:
      - 5433:5432
    volumes:
      - test_postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=coffee_test_bd
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=sami1234

volumes:
  postgres_data:
  test_postgres_data:
