version: '3.9'

services:
  db:
    image: postgres:14-alpine
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=coffee_bd
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password1234

volumes:
  postgres_data:
